# build-pipeline.yml

steps:
  # --- 1. GET SERVICE NAME (Input Step) ---
  - label: "⚙️ Select Service to Build"
    key: "get_service_name"
    prompt: "Please enter the name of the service to build."
    type: input
    fields:
      - text: "SERVICE_NAME"
        key: "SERVICE_NAME"
        required: true

  # --- 2. BUILD AND PUSH TO ECR (Command Step) ---
  - label: "🚀 Build & Push Docker Image for $$SERVICE_NAME"
    key: "build_and_push"
    depends_on: "get_service_name"
    commands:
      # --- 1. CONSOLIDATED VARIABLE DEFINITION AND IMAGE CALCULATION ---
      # All variables that rely on each other MUST be in one shell block.
      - |
        # 1. Retrieve required variables from Meta-data
        SERVICE_NAME="test_dir"
        AWS_ACCOUNT_ID="004095192903"
        AWS_REGION="us-east-1"
        
        # 2. Define/Calculate dependent variables
        BUILD_TAG="${BUILDKITE_COMMIT}_$${SERVICE_NAME}"
        ECR_REGISTRY_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        REPOSITORY_NAME="emr_cluster"
        IMAGE_URI="$${ECR_REGISTRY_URI}/$${REPOSITORY_NAME}"
        DOCKERFILE_PATH="Dockerfile"
        BASE_DIR="."
        
        echo "Calculated Image URI: $${IMAGE_URI}:$${BUILD_TAG}"
        echo "--- Building Image ---"
        docker build \
          --file "$${DOCKERFILE_PATH}" \
          --build-arg SERVICE_NAME="$${SERVICE_NAME}" \
          --tag "$${IMAGE_URI}:$${BUILD_TAG}" \
          .
        echo "--- Pushing Image to ECR ---"
        docker push "$${IMAGE_URI}:$${BUILD_TAG}"
        
        # STORE FOR DOWNSTREAM STEPS
        buildkite-agent meta-data set "IMAGE_URI" "$${IMAGE_URI}"
        buildkite-agent meta-data set "BUILD_TAG" "$${BUILD_TAG}"
        buildkite-agent meta-data set "AWS_REGION" "$${AWS_REGION}"
        buildkite-agent meta-data set "AWS_ACCOUNT_ID" "$${AWS_ACCOUNT_ID}"

  # --- 3. TRIGGER S3 PUSH PIPELINE (Optional Input + Trigger) ---
  - block: "❓ Trigger S3 Asset Push?"
    prompt: "Do you want to extract and push the static assets to S3?"
    key: "ask_s3_push"
    depends_on: "build_and_push"
    fields:
      - select: "S3_CHOICE"
        key: "deploy-type"
        default: "yes"
        required: true
        options:
          - label: "Yes, push to S3"
            value: "yes"
          - label: "No, skip S3 push"
            value: "no"

  - label: "pipeline: Setup pipeline"
    key: "setup_pipline"
    depends_on: "ask_s3_push"
    command: |
          if [ "$$(buildkite-agent meta-data get "deploy-type")" == "yes" ]; then
            buildkite-agent pipeline upload .buildkite/s3-push.yml
          fi
