# build-pipeline.yml

steps:
  # --- 1. GET SERVICE NAME (Input Step) ---
  - label: "⚙️ Select Service to Build"
    key: "get_service_name"
    prompt: "Please enter the name of the service to build."
    type: input
    fields:
      - text: "SERVICE_NAME"
        key: "SERVICE_NAME"
        required: true

  # --- 2. BUILD AND PUSH TO ECR (Command Step) ---
  - label: "🚀 Build & Push Docker Image for $$SERVICE_NAME"
    key: "build_and_push"
    depends_on: "get_service_name"
    commands:
      # --- 1. CONSOLIDATED VARIABLE DEFINITION AND IMAGE CALCULATION ---
      # All variables that rely on each other MUST be in one shell block.
      - |
        # 1. Retrieve required variables from Meta-data
        SERVICE_NAME="test_dir"
        AWS_ACCOUNT_ID="052510803641"
        AWS_REGION="us-east-1"
        
        # 2. Define/Calculate dependent variables
        BUILD_TAG="${BUILDKITE_COMMIT}"
        ECR_REGISTRY_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        REPOSITORY_NAME="emr_cluster_${SERVICE_NAME}" # Uses SERVICE_NAME
        IMAGE_URI="${ECR_REGISTRY_URI}/${REPOSITORY_NAME}" # Uses ECR_REGISTRY_URI
        DOCKERFILE_PATH="."
        BASE_DIR="."
        
        echo "Calculated Image URI: ${IMAGE_URI}:${BUILD_TAG}"
        echo "--- Building Image ---"
        docker build \
          --file "${DOCKERFILE_PATH}" \
          --tag "${IMAGE_URI}:${BUILD_TAG}" \
          "${BASE_DIR}/${SERVICE_NAME}"
        echo "--- Pushing Image to ECR ---"
        docker push "${IMAGE_URI}:${BUILD_TAG}"
        
        # STORE FOR DOWNSTREAM STEPS
        buildkite-agent meta-data set "IMAGE_URI" "${IMAGE_URI}"
        buildkite-agent meta-data set "BUILD_TAG" "${BUILD_TAG}"
        buildkite-agent meta-data set "AWS_REGION" "${AWS_REGION}"
        buildkite-agent meta-data set "AWS_ACCOUNT_ID" "${AWS_ACCOUNT_ID}"

#  # --- 3. TRIGGER S3 PUSH PIPELINE (Optional Input + Trigger) ---
#  - label: "❓ Trigger S3 Asset Push?"
#    key: "ask_s3_push"
#    prompt: "Do you want to extract and push the static assets to S3?"
#    type: input
#    depends_on: "build_and_push"
#    fields:
#      - text: "S3_CHOICE"
#        default: "yes"
#        options:
#          - label: "Yes, push to S3"
#            value: "yes"
#          - label: "No, skip S3 push"
#            value: "no"
#
#  - label: "⬆️ Trigger S3 Push Pipeline"
#    key: "trigger_s3"
#    trigger: "my-s3-pipeline"
#    build:
#      # Pass required information to the triggered pipeline
#      env:
#        SERVICE_NAME: "$$(buildkite-agent meta-data get SERVICE_NAME)"
#        IMAGE_URI: "$$(buildkite-agent meta-data get IMAGE_URI)"
#        BUILD_TAG: "$$(buildkite-agent meta-data get BUILD_TAG)"
#        # Pass the region so the S3 script can use it
#        AWS_REGION: "$$(buildkite-agent meta-data get AWS_REGION)"
#    if: "$$(buildkite-agent meta-data get S3_CHOICE) == 'yes'"

# ... (The rest of the triggers remain the same)