from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    DoubleType,
    ArrayType,
    BooleanType,
)

schema = StructType(
    [
        StructField("id", IntegerType()),
        StructField("title", StringType()),
        StructField("mediaId", IntegerType()),
        StructField("numCollectedTickets", IntegerType()),
        StructField("streamingEvent", BooleanType()),
        StructField("rsvpCount", IntegerType()),
        StructField("announcedAt", StringType()),
        StructField("startsAt", StringType()),
        StructField("endsAt", StringType()),
        StructField("day", StringType()),
        StructField("month", StringType()),
        StructField("year", StringType()),
        StructField("date", StringType()),
        StructField("artistId", IntegerType()),
        StructField("artistName", StringType()),
        StructField("artistNameSlug", StringType()),
        StructField("artistNameFirstLetter", StringType()),
        StructField("artistGenres", ArrayType(StringType())),
        StructField("artistOnTour", BooleanType()),
        StructField("artistTrackerCount", IntegerType()),
        StructField("venueName", StringType()),
        StructField("city", StringType()),
        StructField("venueCountry", StringType()),
        StructField("latitude", DoubleType()),
        StructField("longitude", DoubleType()),
        StructField("streetAddress", StringType()),
        StructField("venueAddress", StringType()),
        StructField("venueRegion", StringType()),
        StructField("venueLocation", StringType()),
        StructField("venueLocationSlug", StringType()),
        StructField("postalCode", StringType()),
        StructField("region", StringType()),
    ]
)


# DataFrame column name -> Target Solr document field names

field_map = {
    "id": "id",
    "title": "title",
    "mediaId": "mediaId",
    "artistId": "artistId",
    "artistName": "artistName",
    "streamingEvent": "streamingEvent",
    "venueName": "venueName",
    "city": "city",
    "venueCountry": "venueCountry",
    "latitude": "latitude",
    "longitude": "longitude",
    "latlong": "latlong",
    "streetAddress": "streetAddress",
    "venueAddress": "venueAddress",
    "venueRegion": "venueRegion",
    "venueLocation": "venueLocation",
    "postalCode": "postalCode",
    "region": "region",
    "artistNameSlug": "artistNameSlug",
    "venueLocationSlug": "venueLocationSlug",
    "announcedAt": "announcedAt",
    "startsAt": "startsAt",
    "endsAt": "endsAt",
    "day": "day",
    "month": "month",
    "year": "year",
    "date": "date",
}